name: ProjectTemplate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - black
  - doctest
  - esbonio # for sphinx
  - ipykernel
  - jupyter
  - matplotlib
  - mypy
  - mypy_extensions
  - numpy
  - pandas
  - pip
  - pylint
  - pyright
  - pytest
  - pytest-mock
  - pytest-pylint
  - python-dotenv
  - scipy
  - sphinx
  - sphinxcontrib
  - sphinx-needs
  - sphinx_rtd_theme
  - scikit-learn
