name: ProjectTemplate Issue Form
description: General template for new issues
title: "New Issue: Description"
labels: ["feat"]
assignees: esther-poniatowski
body: 
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description
